apiVersion: v2
name: kyoo
description: Kyoo is an open source media server alternative to Jellyfin and Plex.

type: application
version: 0.0.0
appVersion: "0.0.0"

icon: https://raw.githubusercontent.com/zoriya/Kyoo/refs/heads/master/icons/icon.svg

dependencies:
- condition: meilisearch.enabled
  name: meilisearch
  repository: https://meilisearch.github.io/meilisearch-kubernetes
  version: 0.17.1
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 18.0.15
- condition: rabbitmq.enabled
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 16.0.14
