{{- if .Values.auth.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.auth.serviceAccount.automount }}
metadata:
  name: {{ include "kyoo.auth.serviceAccountName" . }}
  labels:
    {{- include "kyoo.labels" (dict "context" . "component" .Values.auth.name "name" .Values.auth.name) | nindent 4 }}
  {{- with .Values.auth.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
