apiVersion: v1
kind: Service
metadata:
{{- if .Values.traefikproxy.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.traefikproxy.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ include "kyoo.traefikproxy.fullname" . }}
  labels:
    {{- include "kyoo.labels" (dict "context" . "component" .Values.traefikproxy.name "name" .Values.traefikproxy.name) | nindent 4 }}
    {{- with .Values.traefikproxy.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.traefikproxy.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
    - port: 443
      targetPort: 443
      protocol: TCP
      name: websecure
  selector:
    {{- include "kyoo.selectorLabels" (dict "context" . "name" .Values.traefikproxy.name) | nindent 4 }}
