{{- if .Values.traefikproxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.traefikproxy.serviceAccount.automount }}
metadata:
  name: {{ include "kyoo.traefikproxy.serviceAccountName" . }}
  labels:
    {{- include "kyoo.labels" (dict "context" . "component" .Values.traefikproxy.name "name" .Values.traefikproxy.name) | nindent 4 }}
  {{- with .Values.traefikproxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
