name: Update the documentation

on:
  push:
    branches:
      - master

jobs:
  Building:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz
      - name: Update the docs
        run: |
          rm -rf docs/*
          doxygen Doxyfile
          cd docs
          git config --global user.email "${GITHUB_ACTOR}@github.com";
          git config --global user.name "${GITHUB_ACTOR}";
          git init
          git add -A;
          git commit -m "Deploying the documentation";
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${GITHUB_REPO};
          git checkout -b Documentation
          git push --force origin Documentation;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: "github.com/AnonymusRaccoon/Kyoo"
